export const GET_ALL_COMMENT_API = 'GET_ALL_COMMENT_API'
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'

export const INSERT_COMMENT_API = 'INSERT_COMMENT_API'

export const DELETE_COMMENT_API = 'DELETE_COMMENT_API'

export const EDIT_COMMENT_API = 'EDIT_COMMENT_API'

